[workspace]
authors = ["Amit Klein <a3klein@ucsd.edu>"]
channels = ["conda-forge", "pypi", "pytorch", "nvidia"]
name = "spida"
platforms = ["linux-64"]
version = "0.1.0"
preview = ['pixi-build']

[package]
name = "SPIDA"
version = "0.1.0"

[package.host-dependencies]
hatchling = "*"

[package.build]
backend = { name = "pixi-build-python", version = "0.1*" } 
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]


# Global dependencies 
[dependencies]
python-dotenv = ">=1.1.0,<2"
python = ">=3.10"
ipython = "8.*"
ipywidgets = "8.*"
jupyterlab = "4.*"
ipykernel = "*"
pixi-kernel = ">=0.6.4,<0.7"
click = ">=8.2.2,<9"
rich-click = ">=1.8.9,<2"
papermill = ">=2.6.0,<3"

[pypi-dependencies]
ruff = "*"
spida = { path = "." }

[feature.gpu.system-requirements]
cuda = "12.0"
[feature.gpu.dependencies]
cuda-version = "12.*"
pytorch-gpu = "*"
[feature.gpu.pypi-dependencies]
triton = "*"

[feature.cpu.dependencies]
pytorch-cpu = "*"

# Defining Features
[feature.preprocessing.dependencies]
spatialdata = "*"
spatialdata-io = "*"
spatialdata-plot = "*"
polars = "*"
opentsne = "*"
pynndescent = "*"
statsmodels = "*"
scvi-tools = ">=1.3.2"
scanpy = "*"
leidenalg = "*"
scikit-learn = ">=1.4.1,<1.6"
jax = ">=0.7.0,<0.8"
numpyro = ">=0.19.0,<0.20"
imbalanced-learn = ">=0.12.4,<0.13"
chex = ">=0.1.90,<0.2"
pysal = ">=25.7,<26"
xarray = ">=2024.11.0,<2025"
rioxarray = ">=0.19.0,<0.20"
geopandas = ">=1.1.1,<2"
shapely = ">=2.1.1,<3"
adjusttext = ">=1.3.0,<2"
openpyxl = ">=3.1.5,<4"
mscorefonts = ">=0.0.1,<0.0.2"
# graph-tool = ">=2.98,<3"
[feature.preprocessing.pypi-dependencies] 
allcools = { git = "https://github.com/DingWB/ALLCools" }
opencv-python = "*"
plottable = ">=0.1.5, <0.2"
harmonypy = ">=0.0.10, <0.0.11"
pycomplexheatmap = ">=1.8.2, <2"
hotspotsc = ">=1.1.3, <2"
#scib-metrics = ">=0.5.6, <0.6"

[feature.deepcell.pypi-dependencies]
deepcell = "==0.12.6"
shapely = "*"
supervision = "*"
geopandas = "*"
natsort = "*"
pyarrow = "*" 
[feature.deepcell.dependencies]
python = "<=3.10,>3.8"

[feature.cellpose.dependencies]
python = "3.11.*"
shapely = "*"
geopandas = "*"
supervision = "*"
pyarrow = "*"
scikit-image = "*"
[feature.cellpose.pypi-dependencies]
cellpose = "==4.0.4"

[feature.mapmycells.dependencies]
python="3.10.*"
zarr = "*"
[feature.mapmycells.pypi-dependencies]
cell_type_mapper = { git = "https://github.com/AllenInstitute/cell_type_mapper" }

# Setting environment names for all the features 
[environments]
preprocessing-gpu = ['preprocessing', 'gpu']
preprocessing = ['preprocessing', 'cpu']
deepcell = ["deepcell"]
cellpose = ["cellpose"]
mapmycells = ["mapmycells"]

# Preprocssing Tasks 
[feature.preprocessing.tasks]
# S.help = {cmd = "python main.py ingest_region --help | echo", cwd = "src/spida/io"}
# I.help = {cmd = "python main.py --help | echo", cwd = "src/spida/io"}
# P.help = {cmd = "python main.py filter_cells_region --help | echo", cwd = "src/spida/P"}
spida-S = {cmd = "python -m spida.S"}
spida-P = {cmd = "python -m spida.P"}
spida-I = {cmd = "python -m spida.I"}

[tasks]
lint-fast = "ruff --fix src/"

# [feature.gpu.tasks.install-triton]
# cmd = "pip install triton==2.1.0 --foce-reinstall --no-cache-dir"
# depends-on = ["install"]
